<a href="https://colab.research.google.com/github/Kavitha-2005/Loops_project_python/blob/main/pro1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#Pandas Data Cleaning & Data Analysis Project
#Airline Dataset Project Questions

# part 1 - Dataset Understanding

#1.	Import the Pandas library and load the dataset.
import pandas as pd
a=pd.read_csv('/content/uncleaned_airline_dataset_20_columns (1).csv')
a

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.0,Non-Refundable,NaN,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.0,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,NaN,NON REFUNDABLE,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.0,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.0,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [ ]:
#2.	Display the first 10 rows of the dataset.
a.head(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,Non-Veg,30,not checked,T2,30.0,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,NONE,20.0,checked,unknown,10.0,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.170896,Non-Refundable,Non-Veg,25,checked,T2,10.0,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,NaN,30,unknown,T2,10.0,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,NONE,20.0,checked,T3,10.0,C101
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955,4.000000,refundable,NaN,15,checked,T2,0.0,C103
6,6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060,4.000000,refundable,veg,30,not checked,T2,5.0,C101
8,8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954,2.000000,refundable,Veg,20.0,checked,T1,15.0,C104
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954,4.000000,NON REFUNDABLE,Non-Veg,25,not checked,T1,10.0,C104
10,10,GO_FIRST,G8-392,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954,3.170896,NaN,veg,20,checked,T3,10.0,C105

In [ ]:
#3.	Display the last 10 rows of the dataset.
a.tail(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
300141,300141,Air_India,AI-430,Chennai,Morning,one,Night,Hyderabad,Business,13.67,49,51345,3.000000,NON REFUNDABLE,NONE,20,not checked,unknown,10.0,C103
300142,300142,Air_India,AI-539,Chennai,Evening,one,Morning,Hyderabad,Business,16.00,49,51345,4.000000,refundable,Non-Veg,25,checked,unknown,60.0,C102
300144,300144,Air_India,AI-539,Chennai,Evening,one,Morning,Hyderabad,Business,18.92,49,51345,5.000000,Non-Refundable,Veg,20.0,not checked,T1,10.0,C105
300145,300145,Air_India,AI-430,Chennai,Morning,one,Morning,Hyderabad,Business,23.08,49,51345,4.000000,NON REFUNDABLE,veg,20,checked,T1,60.0,C105
300147,300147,Air_India,AI-569,Chennai,Early_Morning,one,Night,Hyderabad,Business,17.25,49,68739,3.000000,Refundable,veg,25,checked,T2,10.0,C104
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,NaN,25,unknown,T3,0.0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,NON REFUNDABLE,Non-Veg,15,checked,T1,15.0,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.170896,NON REFUNDABLE,NONE,20.0,unknown,unknown,10.0,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,Non-Veg,15,unknown,T2,5.0,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,NON REFUNDABLE,veg,25,unknown,unknown,10.0,C104

In [ ]:
#4.	Find the total number of rows and columns in the dataset.
a.info()

<class 'pandas.core.frame.DataFrame'>
Index: 250526 entries, 0 to 300152
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   index             250526 non-null  int64
 1   airline           250526 non-null  object
 2   flight            250526 non-null  object
 3   source_city       250526 non-null  object
 4   departure_time    250526 non-null  object
 5   stops             250526 non-null  object
 6   arrival_time      250526 non-null  object
 7   destination_city  250526 non-null  object
 8   class             250526 non-null  object
 9   duration          250526 non-null  float64
 10  days_left         250526 non-null  int64
 11  price             250526 non-null  int64
 12  Passenger_Rating  250526 non-null  float64
 13  Ticket_Type       200200 non-null  object
 14  Meal_Option       200523 non-null  object
 15  Baggage_kg        250526 non-null  object
 16  Checkin_Status    250526 non-null  object
 17  Airport_Terminal  250526 non-null  object
 18  Delay_Minutes     250526 non-null  float64
 19  Customer_ID       250526 non-null  object
dtypes: float64(3), int64(3), object(14)
memory usage: 40.1+ MB

In [ ]:
#5.	Display the list of all column names.
a.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price', 'Passenger_Rating', 'Ticket_Type', 'Meal_Option', 'Baggage_kg',
       'Checkin_Status', 'Airport_Terminal', 'Delay_Minutes', 'Customer_ID'],
      dtype='object')

In [ ]:
# part 2 - Dataset Inspection
#6.	Display the data types of all columns.
a.dtypes

index                 int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
Passenger_Rating    float64
Ticket_Type          object
Meal_Option          object
Baggage_kg           object
Checkin_Status       object
Airport_Terminal     object
Delay_Minutes       float64
Customer_ID          object
dtype: object

In [ ]:
#7.	Display basic statistical summary of the dataset.
a.describe

<bound method NDFrame.describe of          index   airline   flight source_city departure_time stops  \
0            0  SpiceJet  SG-8709       Delhi        Evening  zero
1            1  SpiceJet  SG-8157       Delhi  Early_Morning  zero
2            2   AirAsia   I5-764       Delhi  Early_Morning  zero
3            3   Vistara   UK-995       Delhi        Morning  zero
4            4   Vistara   UK-963       Delhi        Morning  zero
...        ...       ...      ...         ...            ...   ...
300148  300148   Vistara   UK-822     Chennai        Morning   one
300149  300149   Vistara   UK-826     Chennai      Afternoon   one
300150  300150   Vistara   UK-832     Chennai  Early_Morning   one
300151  300151   Vistara   UK-828     Chennai  Early_Morning   one
300152  300152   Vistara   UK-822     Chennai        Morning   one

         arrival_time destination_city     class  duration  days_left  price  \
0               Night           Mumbai   Economy      2.17          1   5953
1             Morning           Mumbai   Economy      2.33          1   5953
2       Early_Morning           Mumbai   Economy      2.17          1   5956
3           Afternoon           Mumbai   Economy      2.25          1   5955
4             Morning           Mumbai   Economy      2.33          1   5955
...               ...              ...       ...       ...        ...    ...
300148        Evening        Hyderabad  Business     10.08         49  69265
300149          Night        Hyderabad  Business     10.42         49  77105
300150          Night        Hyderabad  Business     13.83         49  79099
300151        Evening        Hyderabad  Business     10.00         49  81585
300152        Evening        Hyderabad  Business     10.08         49  81585

        Passenger_Rating     Ticket_Type Meal_Option Baggage_kg  \
0               5.000000             NaN     Non-Veg         30
1               4.000000  Non-Refundable        NONE       20.0
2               3.170896  Non-Refundable     Non-Veg         25
3               1.000000             NaN         NaN         30
4               4.000000             NaN        NONE       20.0
...                  ...             ...         ...        ...
300148          2.000000  Non-Refundable         NaN         25
300149          1.000000  NON REFUNDABLE     Non-Veg         15
300150          3.170896  NON REFUNDABLE        NONE       20.0
300151          4.000000  Non-Refundable     Non-Veg         15
300152          2.000000  NON REFUNDABLE        veg          25

       Checkin_Status Airport_Terminal  Delay_Minutes Customer_ID
0         not checked               T2           30.0        C101
1             checked          unknown           10.0        C103
2            checked                T2           10.0        C105
3             unknown               T2           10.0        C102
4             checked               T3           10.0        C101
...               ...              ...            ...         ...
300148        unknown               T3            0.0        C101
300149        checked               T1           15.0       C104
300150        unknown          unknown           10.0        C103
300151        unknown               T2            5.0       C104
300152        unknown          unknown           10.0       C104

[250526 rows x 20 columns]>

In [ ]:
#8.	Identify which columns contain missing values.
a.columns[a.isnull().any()]

Index(['Ticket_Type', 'Meal_Option'], dtype='object')

In [ ]:
#9.	Count the number of missing values in each column.
a.isnull().sum()

index                   0
airline                 0
flight                  0
source_city             0
departure_time          0
stops                   0
arrival_time            0
destination_city        0
class                   0
duration                0
days_left               0
price                   0
Passenger_Rating        0
Ticket_Type         50326
Meal_Option         50003
Baggage_kg              0
Checkin_Status          0
Airport_Terminal        0
Delay_Minutes           0
Customer_ID             0
dtype: int64

In [ ]:
#10.	Display the number of unique values in each column.
a.nunique()

index               250526
airline                  6
flight                1555
source_city              6
departure_time           6
stops                    3
arrival_time             6
destination_city         6
class                    2
duration               474
days_left               49
price                11566
Passenger_Rating         6
Ticket_Type              4
Meal_Option              4
Baggage_kg               5
Checkin_Status           4
Airport_Terminal         4
Delay_Minutes            6
Customer_ID              5
dtype: int64

In [10]:
#part 3 - Data Cleaning
# 11.	Replace missing values in Passenger_Rating with the mean value.

a['Passenger_Rating'].fillna(a['Passenger_Rating'].mean(),inplace=True)

/tmp/ipykernel_10956/2739951595.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Passenger_Rating'].fillna(a['Passenger_Rating'].mean(),inplace=True)

In [11]:
#12.	Replace missing values in Meal_Option with "Unknown".
a['Meal_Option'].fillna(("unknown"))

0         Non-Veg
1            NONE
2         Non-Veg
3         unknown
4            NONE
           ...
300148    unknown
300149    Non-Veg
300150       NONE
300151    Non-Veg
300152       veg
Name: Meal_Option, Length: 300153, dtype: object

In [12]:
#14.	Remove rows where Customer_ID is missing.
a.dropna(subset=['Customer_ID'],inplace=True)

In [ ]:
#15.	Verify that missing values are handled.
a.isnull().sum()

index                   0
airline                 0
flight                  0
source_city             0
departure_time          0
stops                   0
arrival_time            0
destination_city        0
class                   0
duration                0
days_left               0
price                   0
Passenger_Rating        0
Ticket_Type         50326
Meal_Option         50003
Baggage_kg              0
Checkin_Status          0
Airport_Terminal        0
Delay_Minutes           0
Customer_ID             0
dtype: int64

In [30]:
#part 4 - String Cleaning
#16.	Remove leading and trailing spaces from all string columns.
a.columns=a.columns.str.strip()

In [31]:
#17.	Convert Meal_Option values to lowercase.
a['Meal_Option']=a['Meal_Option'].str.lower()

In [13]:
#18.	Convert Ticket_Type values to proper format (Refundable / Non-Refundable).
a['Ticket_Type'].replace({'nan':'Non-Refundable','refundable':'Refundable','NON REFUNDABLE':'Non-Refundable',' refundable ':'Refundable'},inplace=True)
a

/tmp/ipykernel_10956/49157656.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Ticket_Type'].replace({'nan':'Non-Refundable','refundable':'Refundable','NON REFUNDABLE':'Non-Refundable',' refundable ':'Refundable'},inplace=True)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,NaN,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,Non-Refundable,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,Non-Refundable,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,Non-Refundable,veg,25,NaN,NaN,unknown,C104

In [17]:
#19.	Standardize Checkin_Status values.
a['Checkin_Status'].replace({'Not Checked':'not checked', 'checked-in':'checked','checked':'checked', 'nan':'not checked','Checked-In':'checked'},inplace=True)

In [18]:
#20.	Standardize Airport_Terminal values to T1, T2, T3 format.
a['Airport_Terminal'].replace({'T2':'T2','terminal-2':'T2', 'T3':'T3', 'T1':'T1', 'Terminal 1':'T1'},inplace=True)

/tmp/ipykernel_10956/3445150966.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Airport_Terminal'].replace({'T2':'T2','terminal-2':'T2', 'T3':'T3', 'T1':'T1', 'Terminal 1':'T1'},inplace=True)

In [19]:
#part 5 - Data Type Cleaning
 #21.	Convert Passenger_Rating column to numeric datatype.
a['Passenger_Rating']=a['Passenger_Rating'].astype('int')

In [20]:
#22.	Convert Baggage_kg values by removing "kg" text.
a['Baggage_kg'].replace({'30kg':30},inplace=True)

/tmp/ipykernel_10956/2349356729.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Baggage_kg'].replace({'30kg':30},inplace=True)

In [ ]:
a['Baggage_kg'].unique()

array([30, 'unknown', '25', '15', '20', nan], dtype=object)

In [23]:
#24.	Replace "unknown" values with NaN.
a['Baggage_kg'] = a['Baggage_kg'].replace('unknown', np.nan)

In [24]:
#13.	Replace missing values in Baggage_kg with the median value.
a['Baggage_kg'].fillna(a['Baggage_kg'].median(),inplace=True)

/tmp/ipykernel_10956/2270186933.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Baggage_kg'].fillna(a['Baggage_kg'].median(),inplace=True)

In [22]:
import numpy as np

In [25]:
a['Delay_Minutes'].unique()

array(['30', '10', 'unknown', nan, '0', '5', ' 15 ', '60'], dtype=object)

In [26]:
a['Delay_Minutes'].replace({'30':30, '10':10,'0':0, '5':5, ' 15 ':15, '60':60},inplace=True)

/tmp/ipykernel_10956/392160535.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Delay_Minutes'].replace({'30':30, '10':10,'0':0, '5':5, ' 15 ':15, '60':60},inplace=True)

In [27]:
#24.	Replace "unknown" values with NaN.
a['Delay_Minutes'].replace('unknown',np.nan,inplace=True)

/tmp/ipykernel_10956/4230929751.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  a['Delay_Minutes'].replace('unknown',np.nan,inplace=True)

In [28]:
a['Delay_Minutes'].fillna(a['Delay_Minutes'].median(),inplace=True)

In [29]:
#23.	Convert Delay_Minutes column into integer datatype.
a['Delay_Minutes'].astype(int)

0         30
1         10
2         10
3         10
4         10
          ..
300148     0
300149    15
300150    10
300151     5
300152    10
Name: Delay_Minutes, Length: 250526, dtype: int64

In [ ]:
#25.	Verify the updated data types.
print(a.dtypes)

index                 int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
Passenger_Rating      int64
Ticket_Type          object
Meal_Option          object
Baggage_kg           object
Checkin_Status       object
Airport_Terminal     object
Delay_Minutes       float64
Customer_ID          object
dtype: object

In [ ]:
#part 6 - Duplicate Data Handling
#26.	Check whether duplicate rows exist in the dataset.
a.duplicated().any()

np.False_

In [ ]:
#27.	Count the number of duplicate rows.
a.duplicated().sum()

np.int64(0)

In [ ]:
#28.	Remove duplicate rows from the dataset.
a.drop_duplicates()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5,NaN,non-veg,30,not checked,T2,30.0,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4,Non-Refundable,none,NaN,checked,NaN,10.0,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3,Non-Refundable,non-veg,25,checked,T2,10.0,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1,NaN,NaN,30,NaN,T2,10.0,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4,NaN,none,NaN,checked,T3,10.0,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2,Non-Refundable,NaN,25,NaN,T3,0.0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1,Non-Refundable,non-veg,15,checked,T1,15.0,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3,Non-Refundable,none,NaN,NaN,NaN,10.0,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4,Non-Refundable,non-veg,15,NaN,T2,5.0,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2,Non-Refundable,veg,25,NaN,NaN,10.0,C104

In [ ]:
# part 7 - Basic Data Analysis
#29.	Find the total number of flights in the dataset.
a['flight'].count()

np.int64(250526)

In [ ]:
#30.	Find the number of unique airlines.
a['airline'].unique()

array(['SpiceJet', 'AirAsia', 'Vistara', 'GO_FIRST', 'Indigo',
       'Air_India'], dtype=object)

In [ ]:
#31.	Display the list of unique source cities.
a['source_city'].unique()

array(['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai'],
      dtype=object)

In [ ]:
#32.	Display the list of unique destination cities.
a['destination_city'].unique()

array(['Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai', 'Delhi'],
      dtype=object)

In [ ]:
#33.	Count flights for each airline.
a.groupby('airline')['flight'].count()

airline
AirAsia       13402
Air_India     67465
GO_FIRST      19368
Indigo        36105
SpiceJet       7530
Vistara      106656
Name: flight, dtype: int64

In [ ]:
# part 8 - Price Analysis
#34.	Find the average ticket price.
a.groupby('Ticket_Type')['price'].mean()

Ticket_Type
Non-Refundable    20835.275917
Refundable        20896.328991
Name: price, dtype: float64

In [ ]:
#35.	Find the maximum ticket price.
a.groupby('Ticket_Type')['price'].max()

Ticket_Type
Non-Refundable    117307
Refundable        116562
Name: price, dtype: int64

In [ ]:
#36.	Find the minimum ticket price.
a.groupby('Ticket_Type')['price'].min()

Ticket_Type
 refundable       1105
NON REFUNDABLE    1105
Non-Refundable    1105
Refundable        1105
Name: price, dtype: int64

In [ ]:
#36.	Find the minimum ticket price.
a.groupby('airline')['price'].min()

airline
AirAsia      1105
Air_India    1526
GO_FIRST     1105
Indigo       1105
SpiceJet     1106
Vistara      1714
Name: price, dtype: int64

In [ ]:
a['flight'].unique()

array(['SG-8709', 'SG-8157', 'I5-764', ..., '6E-7259', 'AI-433', 'AI-652'],
      dtype=object)

In [ ]:
#38.	Display the top 5 most expensive flights.
a.groupby('flight')['price'].nlargest(5)

flight
0.00E+00  97174       8832
          100735      7220
          97470       6092
          98232       5178
          98608       5178
                     ...
UK-996    230092    114523
          241548    111964
          241599    111964
          230088    105764
          230089    105764
Name: price, Length: 7509, dtype: int64

In [ ]:
# part 9 - City Analysis
#39.	Find the number of flights from each source city.
a.groupby('source_city')['flight'].count()

source_city
Bangalore    43400
Chennai      32321
Delhi        51252
Hyderabad    33995
Kolkata      38765
Mumbai       50793
Name: flight, dtype: int64

In [ ]:
#40.	Find the number of flights to each destination city.
a.groupby('destination_city')['flight'].count()

destination_city
Bangalore    42789
Chennai      33733
Delhi        47760
Hyderabad    35641
Kolkata      41396
Mumbai       49207
Name: flight, dtype: int64

In [ ]:
#41.	Identify the source city with the most flights.
a.groupby('source_city')['flight'].max()

source_city
Bangalore    UK-897
Chennai      UK-838
Delhi        UK-995
Hyderabad    UK-898
Kolkata      UK-778
Mumbai       UK-996
Name: flight, dtype: object

In [ ]:
#42.	Find the average ticket price for each source city.
a.groupby('source_city')['price'].min()

source_city
Bangalore    1603
Chennai      1105
Delhi        1998
Hyderabad    1543
Kolkata      2436
Mumbai       1890
Name: price, dtype: int64

In [ ]:
# part 10 - Flight Details Analysis
#43.	Count flights based on number of stops.
a.groupby('flight')['price'].min()

flight
0.00E+00     2201
6.00E-102    1755
6.00E-105    4079
6.00E-113    2201
6.00E-121    1543
             ...
UK-988       2339
UK-993       2700
UK-994       2339
UK-995       2700
UK-996       2339
Name: price, Length: 1555, dtype: int64

In [ ]:
#44.	Find the average price based on flight class.
a.groupby('flight')['stops'].count()

flight
0.00E+00       42
6.00E-102      33
6.00E-105       5
6.00E-113      37
6.00E-121      19
             ...
UK-988       1133
UK-993        738
UK-994       1064
UK-995        836
UK-996       1070
Name: stops, Length: 1555, dtype: int64

In [ ]:
#45.	Find the airline with the highest average passenger rating.
a.groupby('airline')['Passenger_Rating'].mean().max()

3.140437835605122

In [ ]:
#46.	Count flights based on departure time.
a.groupby('flight')['departure_time'].count()

flight
0.00E+00       42
6.00E-102      33
6.00E-105       5
6.00E-113      37
6.00E-121      19
             ...
UK-988       1133
UK-993        738
UK-994       1064
UK-995        836
UK-996       1070
Name: departure_time, Length: 1555, dtype: int64

In [ ]:
# part 11 - Delay Analysis
#47.	Find the average delay minutes of flights.

a.groupby('flight')['Delay_Minutes'].count()

flight
0.00E+00       42
6.00E-102      33
6.00E-105       5
6.00E-113      37
6.00E-121      19
             ...
UK-988       1133
UK-993        738
UK-994       1064
UK-995        836
UK-996       1070
Name: Delay_Minutes, Length: 1555, dtype: int64

In [ ]:
#48.	Display flights delayed more than 30 minutes.
a.loc[a['Delay_Minutes'] > 30, ['flight']]

         flight
12      6E-5001
28      SG-8169
33       UK-817
34       UK-819
37       AI-453
...         ...
300100   UK-838
300106   UK-834
300136   UK-834
300142   AI-539
300145   AI-430

[31318 rows x 1 columns]

In [ ]:
#Part 12 – Final Output (2 Questions)
#50.	Display the final shape of the cleaned dataset.
a.shape

(250526, 20)

In [42]:
a.isnull().any()

index               False
airline             False
flight              False
source_city         False
departure_time      False
stops               False
arrival_time        False
destination_city    False
class               False
duration            False
days_left           False
price               False
Passenger_Rating    False
Ticket_Type         False
Meal_Option         False
Baggage_kg          False
Checkin_Status      False
Airport_Terminal    False
Delay_Minutes       False
Customer_ID         False
dtype: bool

In [32]:
a['Airport_Terminal'].fillna("unknown",inplace = True)

/tmp/ipykernel_10956/2113176064.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Airport_Terminal'].fillna("unknown",inplace = True)

In [33]:
a['Checkin_Status'].fillna("unknown",inplace=True)

/tmp/ipykernel_10956/1307339165.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Checkin_Status'].fillna("unknown",inplace=True)

In [38]:
a['Passenger_Rating'].unique()

array([5, 4, 3, 1, 2])

In [34]:
a['Passenger_Rating'].fillna(a['Passenger_Rating'].mean(),inplace=True)

/tmp/ipykernel_10956/3418084460.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Passenger_Rating'].fillna(a['Passenger_Rating'].mean(),inplace=True)

In [37]:
a['Ticket_Type'].unique()

array(['unknown', 'Non-Refundable', 'Refundable'], dtype=object)

In [36]:
a['Ticket_Type'].fillna("unknown",inplace=True)

/tmp/ipykernel_10956/2109093837.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Ticket_Type'].fillna("unknown",inplace=True)

In [40]:
a['Meal_Option'].unique()

array(['non-veg', 'none', nan, 'veg ', 'veg'], dtype=object)

In [41]:
a['Meal_Option'].fillna("unknown",inplace=True)

/tmp/ipykernel_10956/3603180758.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  a['Meal_Option'].fillna("unknown",inplace=True)